const medicalData = [
    // 動詞編
    { type: 'verb', category: '調査・実施', term: 'conduct / perform', meaning: '研究や解析を「実施する」' },
    { type: 'verb', category: '調査・実施', term: 'administer', meaning: '薬剤などを「投与する」' },
    { type: 'verb', category: '調査・実施', term: 'enroll / recruit', meaning: '被験者を「登録・リクルートする」' },
    { type: 'verb', category: '調査・実施', term: 'assign / allocate', meaning: '対象を群に「割り当てる」' },
    { type: 'verb', category: '調査・実施', term: 'undergo', meaning: '患者が検査や治療を「受ける」' },
    { type: 'verb', category: '調査・実施', term: 'extract', meaning: 'データや成分を「抽出する」' },
    { type: 'verb', category: '調査・実施', term: 'exclude', meaning: '基準外の対象を「除外する」' },
    { type: 'verb', category: '調査・実施', term: 'collect', meaning: 'サンプルや情報を「収集する」' },
    { type: 'verb', category: '調査・実施', term: 'comprise / consist of', meaning: '〜で「構成される」' },
    
    { type: 'verb', category: '結果の提示', term: 'show / demonstrate', meaning: '明確に「示す」「証明する」' },
    { type: 'verb', category: '結果の提示', term: 'indicate / suggest', meaning: 'データが「示す」「示唆する」' },
    { type: 'verb', category: '結果の提示', term: 'report', meaning: '知見を「報告する」' },
    { type: 'verb', category: '結果の提示', term: 'observe', meaning: '現象を「認める」「観察する」' },
    { type: 'verb', category: '結果の提示', term: 'identify', meaning: '原因や因子を「特定する」' },
    { type: 'verb', category: '結果の提示', term: 'reveal', meaning: '隠れていた事実を「明らかにする」' },
    { type: 'verb', category: '結果の提示', term: 'present', meaning: '症例やデータを「提示する」' },
    { type: 'verb', category: '結果の提示', term: 'detect', meaning: '微量な変化や物質を「検出する」' },

    { type: 'verb', category: '比較・分析', term: 'evaluate / assess', meaning: '効果や質を「評価・査定する」' },
    { type: 'verb', category: '比較・分析', term: 'investigate / examine', meaning: '詳細に「調査・検討する」' },
    { type: 'verb', category: '比較・分析', term: 'compare', meaning: 'AとBを「比較する」' },
    { type: 'verb', category: '比較・分析', term: 'contrast', meaning: '対照的な違いを「際立たせる」' },
    { type: 'verb', category: '比較・分析', term: 'correlate / associate', meaning: '因子間に「相関・関連がある」' },
    { type: 'verb', category: '比較・分析', term: 'quantify', meaning: '性質を「数値化・定量化する」' },
    { type: 'verb', category: '比較・分析', term: 'normalize', meaning: '条件を「正規化・標準化する」' },
    { type: 'verb', category: '比較・分析', term: 'stratify', meaning: 'グループを「層別化する」' },
    { type: 'verb', category: '比較・分析', term: 'adjust', meaning: '交絡因子などを「調整する」' },
    { type: 'verb', category: '比較・分析', term: 'overlap', meaning: '範囲や性質が「重複する」' },

    { type: 'verb', category: '影響・因果', term: 'affect / influence', meaning: '〜に「影響を与える」' },
    { type: 'verb', category: '影響・因果', term: 'result in / lead to', meaning: '〜という「結果になる」「つながる」' },
    { type: 'verb', category: '影響・因果', term: 'contribute to', meaning: '〜の「一因となる」「寄与する」' },
    { type: 'verb', category: '影響・因果', term: 'trigger / induce', meaning: '反応を「誘発する」「引き起こす」' },
    { type: 'verb', category: '影響・因果', term: 'inhibit / suppress', meaning: '反応を「抑制・阻害する」' },
    { type: 'verb', category: '影響・因果', term: 'promote / facilitate', meaning: 'プロセスを「促進・助長する」' },
    { type: 'verb', category: '影響・因果', term: 'exacerbate', meaning: '症状を「悪化させる」' },
    { type: 'verb', category: '影響・因果', term: 'alleviate / ameliorate', meaning: '苦痛や状態を「緩和・改善する」' },
    { type: 'verb', category: '影響・因果', term: 'modulate', meaning: '機能を「調節・変調する」' },
    { type: 'verb', category: '影響・因果', term: 'mediate', meaning: '因子が作用を「仲介・媒介する」' },
    { type: 'verb', category: '影響・因果', term: 'interfere with', meaning: '〜を「妨害・干渉する」' },

    { type: 'verb', category: '考察・主張', term: 'elucidate', meaning: 'メカニズムを「解明する」' },
    { type: 'verb', category: '考察・主張', term: 'confirm / validate', meaning: '妥当性を「確認・検証する」' },
    { type: 'verb', category: '考察・主張', term: 'postulate / hypothesize', meaning: '仮説を「立てる・前提とする」' },
    { type: 'verb', category: '考察・主張', term: 'speculate', meaning: '論理的推測を行う（不確実性あり）' },
    { type: 'verb', category: '考察・主張', term: 'infer', meaning: '証拠から結論を「推論する」' },
    { type: 'verb', category: '考察・主張', term: 'highlight / emphasize', meaning: '重要性を「強調する」' },
    { type: 'verb', category: '考察・主張', term: 'conclude', meaning: '最終的な「結論を出す」' },
    { type: 'verb', category: '考察・主張', term: 'extrapolate', meaning: '結果を他へ「外挿する」' },
    { type: 'verb', category: '考察・主張', term: 'warrant', meaning: 'さらなる調査を「必要とする」' },

    // 形容詞編
    { type: 'adj', category: '重要性', term: 'significant', meaning: '統計的に「有意な」「重要な」' },
    { type: 'adj', category: '重要性', term: 'prominent / marked', meaning: '変化や差異が「顕著な」' },
    { type: 'adj', category: '重要性', term: 'substantial / considerable', meaning: '数量や影響が「かなりの」' },
    { type: 'adj', category: '重要性', term: 'noteworthy / remarkable', meaning: '注目すべき「著しい」' },
    { type: 'adj', category: '重要性', term: 'pivotal / crucial', meaning: '結論を左右する「極めて重要な」' },
    { type: 'adj', category: '重要性', term: 'fundamental', meaning: '根底に関わる「根本的な」' },

    { type: 'adj', category: '関連性', term: 'relevant', meaning: '内容が「関連した」「適切な」' },
    { type: 'adj', category: '関連性', term: 'consistent', meaning: '他と「一致している」' },
    { type: 'adj', category: '関連性', term: 'associated / related', meaning: '〜と「関連のある」' },
    { type: 'adj', category: '関連性', term: 'comparable', meaning: '能力や数値が「同等の」' },
    { type: 'adj', category: '関連性', term: 'compatible', meaning: '矛盾なく「両立する」' },
    { type: 'adj', category: '関連性', term: 'proportional', meaning: '数値が「比例した」' },

    { type: 'adj', category: '正確性', term: 'robust', meaning: '統計的・科学的に「強固な」' },
    { type: 'adj', category: '正確性', term: 'authentic', meaning: '捏造のない「本物の」' },
    { type: 'adj', category: '正確性', term: 'valid', meaning: '論理的に「妥当な」「有効な」' },
    { type: 'adj', category: '正確性', term: 'accurate / precise', meaning: '「正確な」「精密な」' },
    { type: 'adj', category: '正確性', term: 'reliable', meaning: '再現性があり「信頼できる」' },
    { type: 'adj', category: '正確性', term: 'stringent', meaning: '基準などが「厳格な」' },
    { type: 'adj', category: '正確性', term: 'definitive', meaning: '疑いようのない「決定的な」' },

    { type: 'adj', category: '臨床状態', term: 'eligible', meaning: '選択基準に「合致した」「適格な」' },
    { type: 'adj', category: '臨床状態', term: 'adverse', meaning: '副作用など「有害な」' },
    { type: 'adj', category: '臨床状態', term: 'effective / efficacious', meaning: '治療に「効果がある」' },
    { type: 'adj', category: '臨床状態', term: 'resilient', meaning: '「回復力のある」「抵抗力のある」' },
    { type: 'adj', category: '臨床状態', term: 'prevalent', meaning: '疾患が「広く見られる」' },
    { type: 'adj', category: '臨床状態', term: 'acute / chronic', meaning: '「急性の」／「慢性の」' },
    { type: 'adj', category: '臨床状態', term: 'refractory / resistant', meaning: '治療に「抵抗性のある」' },
    { type: 'adj', category: '臨床状態', term: 'asymptomatic', meaning: '「無症状の」' },

    { type: 'adj', category: '優先度・範囲', term: 'primary / secondary', meaning: '「主要な」／「副次的な」' },
    { type: 'adj', category: '優先度・範囲', term: 'preliminary', meaning: '本試験前の「予備的な」' },
    { type: 'adj', category: '優先度・範囲', term: 'comprehensive', meaning: '多角的な「包括的な」' },
    { type: 'adj', category: '優先度・範囲', term: 'specific', meaning: '特定の条件に絞った「特異的な」' },
    { type: 'adj', category: '優先度・範囲', term: 'extensive', meaning: '広範囲にわたる「広範な」' },
    { type: 'adj', category: '優先度・範囲', term: 'prospective / retrospective', meaning: '「前向きの」／「後ろ向きの」' },

    // 副詞編
    { type: 'adv', category: '統計・強度', term: 'significantly', meaning: '統計学的に「有意に」' },
    { type: 'adv', category: '統計・強度', term: 'relatively', meaning: '「比較的」' },
    { type: 'adv', category: '統計・強度', term: 'absolutely', meaning: '例外なく「完全に」' },
    { type: 'adv', category: '統計・強度', term: 'notably / remarkably', meaning: '「著しく」' },
    { type: 'adv', category: '統計・強度', term: 'strikingly', meaning: '「際立って」' },
    { type: 'adv', category: '統計・強度', term: 'considerably / substantially', meaning: '「かなり」「相当に」' },
    { type: 'adv', category: '統計・強度', term: 'extensively', meaning: '「詳細に（手広く）」' },
    { type: 'adv', category: '統計・強度', term: 'drastically', meaning: '「徹底的に（急激に）」' },
    { type: 'adv', category: '統計・強度', term: 'profoundly', meaning: '「深く（多大に）」' },
    { type: 'adv', category: '統計・強度', term: 'radically', meaning: '「根本から」「劇的に」' },
    { type: 'adv', category: '統計・強度', term: 'sufficiently / adequately', meaning: '「十分に」「適切に」' },
    { type: 'adv', category: '統計・強度', term: 'moderately', meaning: '「適度に」' },
    { type: 'adv', category: '統計・強度', term: 'slightly / marginally', meaning: '「わずかに」' },

    { type: 'adv', category: '時間・頻度', term: 'subsequently', meaning: 'その経過の「その後に」' },
    { type: 'adv', category: '時間・頻度', term: 'periodically', meaning: '一定間隔で「周期的に」' },
    { type: 'adv', category: '時間・頻度', term: 'simultaneously / concomitantly', meaning: '「同時に」「付随して」' },
    { type: 'adv', category: '時間・頻度', term: 'chronologically', meaning: '「時系列順に」' },
    { type: 'adv', category: '時間・頻度', term: 'consistently', meaning: '「一貫して」' },
    { type: 'adv', category: '時間・頻度', term: 'intermittently', meaning: '「断続的に」' },
    { type: 'adv', category: '時間・頻度', term: 'globally', meaning: '「全体的に」' },
    { type: 'adv', category: '時間・頻度', term: 'sequentially', meaning: '「順次（連続的に）」' },

    { type: 'adv', category: '確信度', term: 'undoubtedly', meaning: '疑いようなく「確実に」' },
    { type: 'adv', category: '確信度', term: 'arguably', meaning: 'ほぼ間違いなく「確実に」' },
    { type: 'adv', category: '確信度', term: 'presumably / putatively', meaning: '「おそらく」「推定上」' },
    { type: 'adv', category: '確信度', term: 'plausibly', meaning: '「もっともらしく」' },
    { type: 'adv', category: '確信度', term: 'conceivably / potentially', meaning: '「ひょっとすると」「潜在的に」' },
    { type: 'adv', category: '確信度', term: 'tentatively', meaning: '「暫定的に」' },
    { type: 'adv', category: '確信度', term: 'allegedly', meaning: '「伝えられるところによれば」' },
    { type: 'adv', category: '確信度', term: 'ostensibly', meaning: '「一見したところ」' },

    { type: 'adv', category: '限定・特定', term: 'specifically', meaning: '「具体的には」' },
    { type: 'adv', category: '限定・特定', term: 'respectively', meaning: 'AとBは「それぞれ」' },
    { type: 'adv', category: '限定・特定', term: 'solely / exclusively', meaning: '「ただ一つ」「独占的に」' },
    { type: 'adv', category: '限定・特定', term: 'primarily / largely', meaning: '「第一に」「主に」' },
    { type: 'adv', category: '限定・特定', term: 'essentially / intrinsically', meaning: '「本質的に」「基本的には」' },
    { type: 'adv', category: '限定・特定', term: 'narrowly / strictly', meaning: '「限定的に」「厳格に」' },
    { type: 'adv', category: '限定・特定', term: 'merely', meaning: '「単に（過ぎない）」' },
    { type: 'adv', category: '限定・特定', term: 'incidentally', meaning: '「ちなみに」' },

    { type: 'adv', category: '比較・論理', term: 'conversely', meaning: '「逆に」' },
    { type: 'adv', category: '比較・論理', term: 'unexpectedly', meaning: '「予期せず」' },
    { type: 'adv', category: '比較・論理', term: 'similarly / likewise', meaning: '「同様に」' },
    { type: 'adv', category: '比較・論理', term: 'comparably', meaning: '「同等に」' },
    { type: 'adv', category: '比較・論理', term: 'contrary to...', meaning: '〜とは「反対に」' },
    { type: 'adv', category: '比較・論理', term: 'accordingly / consequently', meaning: '「それに応じて」「結果として」' },
    { type: 'adv', category: '比較・論理', term: 'paradoxically', meaning: '「逆説的に」' },
    { type: 'adv', category: '比較・論理', term: 'inevitably', meaning: '「必然的に」' },
    { type: 'adv', category: '比較・論理', term: 'universally', meaning: '「普遍的に」' },
    { type: 'adv', category: '比較・論理', term: 'notwithstanding', meaning: '「〜にもかかわらず」' },

    // 熟語編
    { type: 'phrase', category: '因果関係', term: 'lead to / result in', meaning: '〜という結果につながる' },
    { type: 'phrase', category: '因果関係', term: 'due to / owing to', meaning: '〜が原因で' },
    { type: 'phrase', category: '因果関係', term: 'stem from / derive from', meaning: '〜に起因する' },
    { type: 'phrase', category: '因果関係', term: 'be associated with', meaning: '〜と関連している' },
    { type: 'phrase', category: '因果関係', term: 'attribute A to B', meaning: 'Aの原因はBであると考える' },
    { type: 'phrase', category: '因果関係', term: 'give rise to', meaning: '新しい事態を生じさせる' },
    { type: 'phrase', category: '因果関係', term: 'contribute to', meaning: '〜の一因となる' },

    { type: 'phrase', category: '根拠・参照', term: 'according to', meaning: '〜によれば' },
    { type: 'phrase', category: '根拠・参照', term: 'in accordance with', meaning: 'ガイドライン等に準拠して' },
    { type: 'phrase', category: '根拠・参照', term: 'based on', meaning: '〜を根拠として' },
    { type: 'phrase', category: '根拠・参照', term: 'consistent with', meaning: '〜と一致している' },
    { type: 'phrase', category: '根拠・参照', term: 'in line with', meaning: '先行研究等と一致して' },
    { type: 'phrase', category: '根拠・参照', term: 'with respect to', meaning: '〜の点に関しては' },
    { type: 'phrase', category: '根拠・参照', term: 'refer to', meaning: '〜を参照する' },

    { type: 'phrase', category: '比較・対照', term: 'compared with', meaning: '〜と比較して' },
    { type: 'phrase', category: '比較・対照', term: 'in contrast to', meaning: '〜とは対照的に' },
    { type: 'phrase', category: '比較・対照', term: 'regardless of', meaning: '〜に関わらず' },
    { type: 'phrase', category: '比較・対照', term: 'apart from', meaning: '〜を除いて' },
    { type: 'phrase', category: '比較・対照', term: 'be superior / inferior to', meaning: '〜より優れている／劣っている' },
    { type: 'phrase', category: '比較・対照', term: 'be equivalent to', meaning: '〜と同等である' },

    { type: 'phrase', category: '手法・実施', term: 'carry out / conduct', meaning: '試験や解析を実行する' },
    { type: 'phrase', category: '手法・実施', term: 'aim to / be designed to', meaning: '〜を目的とする' },
    { type: 'phrase', category: '手法・実施', term: 'focus on', meaning: '〜に焦点を当てる' },
    { type: 'phrase', category: '手法・実施', term: 'range from A to B', meaning: '範囲がAからBにわたる' },
    { type: 'phrase', category: '手法・実施', term: 'in particular', meaning: '「特に」' },
    { type: 'phrase', category: '手法・実施', term: 'be restricted to', meaning: '〜に限定される' },

    { type: 'phrase', category: '考察・結論', term: 'in light of', meaning: '〜を考慮すると' },
    { type: 'phrase', category: '考察・結論', term: 'take into account', meaning: '〜を考慮に入れる' },
    { type: 'phrase', category: '考察・結論', term: 'on the other hand', meaning: '一方で' },
    { type: 'phrase', category: '考察・結論', term: 'in conclusion', meaning: '結論として' },
    { type: 'phrase', category: '考察・結論', term: 'furthermore / in addition', meaning: 'さらに／加えて' },
    { type: 'phrase', category: '考察・結論', term: 'point out', meaning: '事実を指摘する' }
];