/* ============================================================
   awl.js — Academic Word List (Coxhead 2000)
   570 word families, sublists 1-10
   医学論文解析用に医学特有アカデミック語を追記
   ============================================================ */

const AWL_WORDS = new Set([
  // Sublist 1
  "analyse","approach","area","assess","assume","authority","available",
  "benefit","concept","consistent","constitutional","context","contract",
  "create","data","definition","derived","distribution","economic","environment",
  "established","estimate","evidence","export","factors","financial","formula",
  "function","identified","income","indicate","individual","interpretation",
  "involved","issues","labour","legal","legislation","major","method","occur",
  "percent","period","policy","principle","procedure","process","required",
  "research","response","role","section","sector","significant","similar",
  "source","specific","structure","theory","variables",
  // Sublist 2
  "achieve","acquisition","administration","affect","appropriate","aspects",
  "assistance","categories","chapter","commission","community","complex",
  "computer","conclusion","conduct","consequences","construction","consumer",
  "credit","cultural","design","distinction","elements","equation","evaluation",
  "features","final","focus","impact","injury","institute","investment",
  "items","journal","maintenance","normal","obtained","participation","perceived",
  "positive","potential","previous","primary","professional","project","promote",
  "regime","resolution","resources","restricted","security","sought","select",
  "site","strategies","survey","text","traditional","transfer",
  // Sublist 3
  "alternative","circumstances","comments","compensation","components","consent",
  "considerable","constant","constraints","contribution","convention","coordination",
  "core","corporate","corresponding","criteria","deduction","demonstrate",
  "document","dominant","emphasis","ensure","excluded","framework","funds",
  "illustrated","immigration","implies","initial","instance","interaction",
  "justification","layer","link","location","maximum","minorities","negative",
  "outcomes","partnership","philosophy","physical","proportion","published",
  "reaction","registered","reliance","removed","scheme","sequence","sex",
  "shift","specified","sufficient","task","technical","techniques","technology",
  "validity","volume",
  // Sublist 4
  "access","adequate","annual","apparent","approximated","attitudes","attributed",
  "civil","code","commitment","communication","concentration","conference",
  "contrast","cycle","debate","despite","dimensions","domestic","emerged",
  "error","ethnic","goals","granted","hence","hypothesis","implementation",
  "implications","imposed","integration","internal","investigation","job",
  "label","mechanism","obvious","occupational","option","output","overall",
  "parallel","parameters","phase","predicted","principal","prior","professional",
  "project","promote","regime","resolution","retained","series","statistics",
  "status","stress","subsequent","sum","summary","undertaken",
  // Sublist 5
  "academic","adjustment","alter","amendment","aware","capacity","challenge",
  "clause","compounds","contrary","conversely","demonstrate","display","domain",
  "exposure","external","facilitate","fundamental","generated","generation",
  "image","liberal","licence","logic","marginal","medical","migration","ministry",
  "motivation","neutral","nevertheless","notion","objective","orientation",
  "perspective","precise","prime","psychology","pursue","ratio","rejected",
  "revenue","stability","styles","substitution","sustainable","symbolic",
  "target","transition","trend","version","welfare","whereas",
  // Sublist 6
  "abstract","accurate","acknowledged","aggregate","allocation","assigned",
  "attached","author","bond","brief","capable","cited","cooperative","discrimination",
  "display","diverse","domain","edition","enhanced","estate","exceed",
  "expert","explicit","federal","fees","flexibility","furthermore","gender",
  "ignored","incentive","incidence","incorporated","index","inhibition",
  "initiated","input","intelligence","intervention","isolated","media","mode",
  "modify","monitoring","network","obvious","occupational","option","output",
  "overall","parallel","parameters","plus","principles","professional","project",
  "promote","regime","resolution","retained","simulation","so-called","status",
  "stress","subsequent","sum","summary","undertaken",
  // Sublist 7
  "adaptation","adults","advocate","aid","channel","cited","classical",
  "comprehensive","comprising","confirmed","contrary","declined","deduction",
  "demonstrate","deny","disposal","diversification","drafts","emerged",
  "empirical","excluded","exploitation","findings","guidance","hence",
  "ideological","implementing","implications","implicit","induced","inevitable",
  "infrastructure","inspection","instructions","integrated","intermediate",
  "interpretation","invoked","isolation","justified","maintaining","mechanisms",
  "methodological","minor","motivated","neutral","nevertheless","notion",
  "objective","obtained","orientation","phase","predicted","principal",
  "ratio","recovery","research","restricted","scheme","stability",
  "strategies","subsequent","supplementary","symbolic","transition","trend",
  // Sublist 8
  "abandon","accompanied","accumulation","ambiguous","appendix","appreciation",
  "arbitrary","attitudes","attributed","civil","commenced","compilation",
  "conceived","confirmed","contrary","conversion","core","depression",
  "displacement","dissolution","domination","draft","empirical","exclusion",
  "exploitation","exposure","fluctuation","founded","guidelines","highlighted",
  "implicit","inclination","indigenous","informal","inherent","innovation",
  "instance","isolated","justification","label","liberation","marginal",
  "medium","military","minimal","mutual","norm","overlap","passive","preceding",
  "preliminary","presumption","rational","recovery","reveal","scope",
  "subordinate","succession","supplementary","suspended","symbolic","transition",
  // Sublist 9
  "accommodation","analogy","anticipate","assurance","attained","behalf",
  "bulk","cease","coherent","coincide","commenced","concurrent","confined",
  "controversy","conversely","device","devoted","diminished","encountered",
  "equation","friction","fundamentally","guidelines","highlighted","implicit",
  "inclination","incorporated","infrastructure","innovation","inspection",
  "instruction","integrated","manipulation","minimal","mutual","norm",
  "overlap","passive","preliminary","presumption","rational","recovery",
  "scope","simulation","subordinate","succession","suspended","transition",
  "preliminary","proportion","protocol","recovery","specified","subordinate",
  // Sublist 10
  "adjacent","albeit","assembly","collapse","colleagues","compiled","conceived",
  "contradiction","depression","deviation","displacement","dissolution","domination",
  "founded","furthermore","highlighted","inclination","liberation","manipulation",
  "marginal","mutual","norm","preliminary","proportion","protocol","rational",
  "revision","scope","simulation","subordinate","succession","suspended",
  // Medical academic additions (論文頻出医学アカデミック語)
  "abstract","accuracy","adverse","aggregate","analysis","association","baseline",
  "bias","blinded","calculated","candidemia","causality","characteristic","clinical",
  "cohort","comorbidity","comparison","complication","confidence","confounding",
  "correlation","cross-sectional","database","demographic","diagnosis","diagnostic",
  "efficacy","eligible","endpoint","enrolled","epidemiology","etiology","exclusion",
  "follow-up","frequency","fungemia","hazard","heterogeneity","hospitalization",
  "incidence","inclusion","infection","infectious","interval","limitation",
  "logistic","longitudinal","meta-analysis","microbiology","mortality","multivariate",
  "observational","odds","outcome","pathogen","patient","pediatric","pharmacological",
  "prevalence","prophylaxis","prospective","randomized","regression","relapse",
  "resistance","retrospective","risk","sensitivity","sepsis","specificity",
  "statistically","subgroup","susceptibility","survival","systematic","therapy",
  "treatment","univariate","virulence","antimicrobial","antifungal","bacteremia",
  "bacteriology","pathogenesis","susceptible","resistant","intermediate","breakpoint",
  "minimum","inhibitory","concentration","culture","specimen","isolated","isolate",
  "species","genus","strain","serotype","genotype","phenotype","sequencing",
  "phylogenetic","nosocomial","healthcare","intensive","care","unit","immunocompromised",
  "neutropenia","transplant","catheter","device","bloodstream","disseminated",
  "invasive","systemic","empirical","targeted","prophylactic","therapeutic",
  "attributable","excess","matched","adjusted","unadjusted","crude","pooled",
  "weighted","stratified","mediated","moderated","interact","interact",
  "administered","prescribed","initiated","discontinued","prolonged","duration",
  "dose","dosage","route","intravenous","oral","inhaled","topical",
  "biofilm","virulent","toxin","immune","immunity","innate","adaptive",
  "inflammatory","cytokine","receptor","signaling","pathway","mechanism",
  "mutant","mutation","gene","expression","protein","enzyme","substrate",
]);

// AWL lookup function
function isAWL(word) {
  return AWL_WORDS.has(word.toLowerCase().replace(/[^a-z\-]/g, ''));
}
